README.md

Addresses [Twitter feedback](https://twitter.com/HarshilShah1910/status/742022901231063041) from @harshilshah that pointed out a bug in our README’s implementation of the window setup.
1. Read the change.
2. Test that the new code compiles in a sample project.
This regressed in da010e165645c9c53240bdc06d5702b1f53f93f5.

Fixed README bug in window setup

---

Example/PinpointKitExample.xcodeproj/project.pbxproj
Example/Pods/Pods.xcodeproj/project.pbxproj
PinpointKit.podspec.json
PinpointKit/PinpointKit.xcodeproj/project.pbxproj
PinpointKit/PinpointKit/Sources/BlurAnnotationView.swift
PinpointKit/PinpointKit/Sources/MailSender.swift
PinpointKit/PinpointKit/Sources/Screenshotter.swift
PinpointKit/PinpointKit/Sources/StrokeLayoutManager.swift
PinpointKit/PinpointKit/Sources/UIView+PinpointKit.swift

📝 This is pointing at the new `swift-2.3` branch, not `develop`.
- Runs the migrator in Xcode 8 to update to Swift 2.3 syntax. No syntax changes were performed by the migrator.
- Fixes leftover errors. Follow the commit messages and PR comments for descriptions of changes.

Swift 2.3 Beta 1 Migration

---

Example/PinpointKitExample/AppDelegate.swift
Example/PinpointKitExample/ViewController.swift
PinpointKit/PinpointKit/Sources/Configuration.swift
PinpointKit/PinpointKit/Sources/PinpointKit.swift
PinpointKit/PinpointKit/Sources/ShakeDetectingWindow.swift

Closes #124
The example given in #124 would be nice, but would require exposing `PinpointKit`’s configuration as a `var` would introduce shared mutable state on `PinpointKit`, which is avoided in much of the framework. Instead, I dropped `defaultPinpointKit` and added a convenience initializer to `PinpointKit` to keep things immutable:
```swift
public convenience init(feedbackRecipients: [String], delegate: PinpointKitDelegate? = nil) {
let configuration = Configuration(feedbackRecipients: feedbackRecipients)
self.init(configuration: configuration, delegate: delegate)
}
```
I’m open to discussion on the pros and cons of both approaches. Now, instead of using `PinpointKit.defaultPinpointKit`, for use with `ShakeDetectingWindow`:
```swift
class AppDelegate: UIResponder, …
```

Easier Specification Of Email Recipients

---

Example/PinpointKitExample/ViewController.swift
PinpointKit/PinpointKit/Sources/AnnotationView.swift
PinpointKit/PinpointKit/Sources/ArrowAnnotationView.swift
PinpointKit/PinpointKit/Sources/BlurAnnotationView.swift
PinpointKit/PinpointKit/Sources/BoxAnnotationView.swift
PinpointKit/PinpointKit/Sources/Editing/EditImageViewController.swift
PinpointKit/PinpointKit/Sources/Fonts.swift
PinpointKit/PinpointKit/Sources/InterfaceCustomization.swift
PinpointKit/PinpointKit/Sources/MailSender.swift
PinpointKit/PinpointKit/Sources/PinpointKit+ShakePresentation.swift
PinpointKit/PinpointKit/Sources/PinpointKit.swift
PinpointKit/PinpointKit/Sources/ScreenshotDetector.swift
PinpointKit/PinpointKit/Sources/Screenshotter.swift
PinpointKit/PinpointKit/Sources/Sender.swift
PinpointKit/PinpointKit/Sources/TextAnnotationView.swift
PinpointKit/PinpointKit/Sources/UIColor+Palette.swift

📝 Pointed at `swift-3.0`.
~~📝 Based on #132, please review that first.~~
This completes my full project + example project pass for Swift 3.0. A follow-up PR will be based on this one for running the Swift 3 migrator on Xcode 8 beta 2. If you check out this branch to review, please use Xcode 8 beta 1.
Related:
- https://developer.apple.com/videos/play/wwdc2016/403/
- https://swift.org/documentation/api-design-guidelines/

Swift 3.0 API Guidelines Pass 2

---

Example/PinpointKitExample/ViewController.swift
Example/Pods/Pods.xcodeproj/project.pbxproj
PinpointKit/PinpointKit/Sources/Configuration.swift
PinpointKit/PinpointKit/Sources/Feedback.swift
PinpointKit/PinpointKit/Sources/FeedbackCollector.swift
PinpointKit/PinpointKit/Sources/FeedbackConfiguration.swift
PinpointKit/PinpointKit/Sources/FeedbackNavigationController.swift
PinpointKit/PinpointKit/Sources/FeedbackViewController.swift
PinpointKit/PinpointKit/Sources/MailSender.swift
PinpointKit/PinpointKit/Sources/PinpointKit.swift

Closes #134 by allowing the customization of `Feedback`’s `body` and `title`.
To test with a sample subclass, run `git revert -n e9403c8` in Terminal and see the incorporation of `MySender` in `ViewController.swift`.
This PR makes a few properties on `Feedback` `public var`s instead of `let`s. This allows for interception / copying / modifying of `Feedback` by subclassing `MailSender` as seen in 93b9f71. I’d like to open the discussion on alternatives though, as I don’t think making the developer subclass is necessarily the most ideal solution to specifying an email subject and body.
- Simple for developer to implement.
- Allows for up-to-the-moment variation in feedback data, such as `additionalInformation`, as opposed to another solution in which more feedback information would be …

Allow Customizing Feedback

---

README.md

As the title suggests, this change makes mention of the new Swift branches in the README within the **Requirements** section as proposed in #123.
Feedback / change requests welcome.

Mentions Swift 2.3 and 3.0 Branches in README

---

PinpointKit/PinpointKit/Sources/BarButtonItem.swift
PinpointKit/PinpointKit/Sources/Editing/AnnotationViewFactory.swift
PinpointKit/PinpointKit/Sources/Editing/EditImageViewController.swift
PinpointKit/PinpointKit/Sources/InterfaceCustomization.swift
PinpointKit/PinpointKit/Sources/TextAnnotationView.swift

Adding annotationTextAttributes to InterfaceCustomization. In our case used to disable the shadow for a Text Annotation.
*Update*: Adding textEditingDoneButton to InterfaceCustomization Struct

Adding annotationTextAttributes to InterfaceCustomization

---

Example/PinpointKitExample.xcodeproj/project.pbxproj
Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes/PinpointKit.xcscheme

📝 This PR is pointed to the `swift-2.3` branch.
This PR accepts the following changes suggested by Xcode:
No changes were made when re-running the Swift 2.3 migrator with this version of Xcode.

Swift 2.3 Beta 4 Migration Changes

---

PinpointKit/PinpointKit/Sources/Configuration.swift
PinpointKit/PinpointKit/Sources/Editing/EditImageViewController.swift
PinpointKit/PinpointKit/Sources/InterfaceCustomization.swift

Follow up to #148
- Some cleanup / consistency changes
- Moves default text attributes to private extension to reduce logic in `Appearance` initializer
- Adds clarity about `NSForegroundColorAttributeName` value which isn’t respected since we use a single tint color for _all_ annotations, which should all change together when e.g. an alert is presented.
To text text attribute specification: `git revert -n d07354a`

Follow Up to Adding `annotationTextAttributes` to InterfaceCustomization

---

PinpointKit/PinpointKit/Sources/FeedbackViewController.swift
PinpointKit/PinpointKit/Sources/PinpointKit.swift

Closes #92 
Now, if you push instead of present `FeedbackViewController`, it’ll have a normal back button instead of a dismiss button.

Doesn’t Assume `FeedbackViewController` is Presented Modally

---

PinpointKit/PinpointKit/Sources/Feedback.swift
PinpointKit/PinpointKit/Sources/FeedbackViewController.swift
PinpointKit/PinpointKit/Sources/MailSender.swift

Closes #162
Makes `feedbackConfiguration` non-optional on `Feedback` to begin addressing [this comment](https://github.com/Lickability/PinpointKit/pull/161#discussion_r77398685).
Run the sample project on device and attempt to send feedback, ensuring that you don’t hit the new assertion failure.

Makes `feedbackConfiguration` Non-Optional on `Feedback`

---

Example/Pods/Pods.xcodeproj/project.pbxproj
PinpointKit/PinpointKit/Sources/FeedbackTableViewDataSource.swift
PinpointKit/PinpointKit/Sources/FeedbackViewController.swift
PinpointKit/PinpointKit/Sources/ScreenshotCell.swift
PinpointKit/PinpointKit/Sources/ScreenshotHeaderView.swift

Progress on #128
Fixes an issue in which the table view header height was being miscalculated causing excessive vertical space on the `FeedbackViewController`. This is done by converting the header view to a table view cell.
Note that as a result of using self sizing cells, the checkmark cell is a bit taller now.
1. Run the app on iOS 10 built in the latest Xcode 8 beta.
1. Ensure there’s not excessive space between the screenshot and the label beneath it.
- This is pointed to the `swift-3.0` branch, not `develop`.
- This will need to be duplicated on the `swift-2.3` branch once accepted.
- ~~This is based on the branch from #159, the most up-to-date revision that works in Beta 5. Please ensure that is merged before this to reduce the diff significantly.~~ I’ve merged in #161 so the …

Fixes Gap on FeedbackViewController

---

README.md

The specification was incorrect for including `Core` and `ScreenshotDetector`.
Follow the CocoaPods steps in the README ensuring you successfully are able to add PinpointKit.

Fixes CocoaPods instructions in README

---

PinpointKit/PinpointKit/Sources/Core/MailSender.swift

Fixes an issue in which the mail compose view controller would not properly dismiss. This is an issue with the Swift 3 migration. Since the signature for the `MFMailComposeViewControllerDelegate` method changed from including an `NSError` to an `Error`, the delegate method was no longer called. Other instances of this type of migration issue, such as in `UIApplicationDelegate` came with a warning, but this one did not.
Thanks to @salmankhann for pointing out this issue at #166. Since that PR has other changes that have been addressed in other PRs, this one isolates the mail compose dismissal issue only.
1. Launch the sample project on device using this branch in Xcode 8
1. Tap "Send"
1. Tap "Cancel", ensuring that the mail compose view controller dismisses
1. Tap "Send"
1. Actually send …

Fixes Swift 3 Mail Compose Dismissal Bug

---

Example/PinpointKitExample/ViewController.swift
PinpointKit/PinpointKit/Sources/Core/Editing/EditImageViewController.swift
PinpointKit/PinpointKit/Sources/Core/Editing/Editor.swift
PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift

Replaces #140, which is out-of-date with `develop` and in need of a few requested adjustments.
Allows passing other screenshots to PinpointKit than those taken at the time of presentation.
Note that the intended use is _still_ screenshots, not arbitrary images, but we set the image view’s aspect ratio to `.scaleAspectFit` to better support the edge case of an incorrectly-sized image.
1. `git revert -n 13af816`
1. Tap the image to edit it
1. Verify that the edits remain through multiple dismissals / presentations of the editor
1. Verify that the edits clear when canceling out of Pinpoint all together and then re-opening the editor (this was fixed in 271b08a).
Closes #140 on merge.

Show Existing Screenshots in PinpointKit

---

Example/PinpointKitExample/ViewController.swift
PinpointKit/PinpointKit/Sources/Core/Feedback.swift
PinpointKit/PinpointKit/Sources/Core/MIMEType.swift

Replaces #141, which is out-of-date with develop and in need of a few requested adjustments.
Makes available publicly all of `Feedback` and `MIMEType`, requiring a `public`/ defined member-wise initializer for `ApplicationInformation`.
- `git revert -n 1dee431`, build + run, to prove access to publicized information in the example app.
- Compare to #141 to ensure that I got everything being requested in that PR.
Closes #141 on merge.

Public Access Control for Feedback and MIMEType

---

PinpointKit/PinpointKit/Sources/Core/Editing/EditImageViewController.swift
PinpointKit/PinpointKit/Sources/Core/Editing/EditorDelegate.swift

📝 Based on #182. Please merge that first.
This PR provides clients additional hooks into the `Editor`.
To test, set breakpoints in the default implementations of the new function and ensure they get called when:
- Making any changes to annotations (adding, removing, resizing, deleting via double tap, deleting via menu item) (`editorDidMakeChanges`)
- Dismissing the edit image view controller (`editorDidDismiss`)

Adds More EditorDelegate Methods

---

PinpointKit/PinpointKit/Sources/Core/Editing/EditImageViewController.swift
PinpointKit/PinpointKit/Sources/Core/Editing/Editor.swift
PinpointKit/PinpointKit/Sources/Core/FeedbackViewController.swift

:memo: Based on #182 and #183, please merge those first.
- Makes `screenshot` a `{ get set }` on `Editor` instead of just being able to set it, so that it can be retrieved later if needed.
- Adds `numberOfAnnotations` to `Editor` so that clients can know the number of annotations, to e.g. warn the user of dismissal if they’ve made a certain number of annotations.
To test, you can add a print statement to the default implementation of `editorDidMakeChanges(_:to:)` as follows:
```swift
public func editorDidMakeChanges(_ editor: Editor, to screenshot: UIImage) {
print(editor.numberOfAnnotations)
}
```
Then when you make any edits, ensure the value printed to the console matches the number of annotations on screen.

Adjustments to Editor Protocol

---

Example/PinpointKitExample/ViewController.swift
Example/Pods/Pods.xcodeproj/project.pbxproj
PinpointKit/PinpointKit/Sources/Core/Editing/EditImageViewController.swift
PinpointKit/PinpointKit/Sources/Core/Editing/EditImageViewControllerBarButtonItemProviding.swift
PinpointKit/PinpointKit/Sources/Core/InterfaceCustomization.swift

- Adds the ability to customize bar buttons on `EditImageViewController`
- Introduces a new `Appearance` property, `editorDoneButtonFont`, since the `editorTextAnnotationDoneButtonFont` was being used for more than just the text annotation dismiss button.
- Renames `editorTextAnnotationDoneButtonFont` to `editorTextAnnotationDismissButtonFont` for better disambiguation.
1. Run `git revert -n 0db8fa2`, which uses a custom implementation of `EditImageViewControllerBarButtonItemProviding`.
1. View the test code in `ViewController.swift`, which makes the right bar button item log to the console, and the left bar button item dismiss.
1. Make some modifications like setting `allowsHidingBarButtonItemsWhileEditingTextAnnotations` to `true` in this test implementation, and verify the results.

Bar Button Item Customization

---

PinpointKit/PinpointKit/Sources/Core/Editing/EditImageViewController.swift
PinpointKit/PinpointKit/Sources/Core/Screen.swift
PinpointKit/PinpointKit/Sources/Core/ScreenshotCell.swift

- In #180, a Swift 2.3-specific change, I was asked to add a `UIScreen` extension for `pixelHeight`, to be used in `ScreenshotCell.swift`. I’m adding that here since it was a good suggestion.
- Corrects the documentation of `portraitPixelSize` and makes it a `var` which seems more appropriate.
Ensuring single-pixel separator views don’t appear on the screenshot cell.

Updates to UIScreen Extension

---

PinpointKit/PinpointKit/Sources/Core/Editing/EditorDelegate.swift

Adds a default implementation for `editorWillDismiss(_:with:)` so clients need not add a stub.

Adds Default Implementation of `editorWillDismiss(_:with:)`

---

PinpointKit/PinpointKit/Sources/Core/Editing/EditImageViewController.swift

Makes `EditImageViewController` `open` and non-`final` so that it can be subclassed by clients.
Just make sure the example project builds + runs.

Makes EditImageViewController Subclassable

---

PinpointKit/PinpointKit/Sources/Core/Editing/EditImageViewController.swift
PinpointKit/PinpointKit/Sources/Core/Editing/EditorDelegate.swift
PinpointKit/PinpointKit/Sources/Core/Editing/Tool.swift

This PR improves the `EditorDelegate` and updates `EditImageViewController` to call the appropriate delegate methods. `EditorDelegate` now:
- Is notified of tool selection changes.
- Is notified of more granular changes. Previously, we notified the delegate simply that a change was made. Now we provide more information about the change.
1. `git revert -n d7a82dc`
1. With the simulator running, make all of the different types of `AnnotationChange`s to ensure that the appropriate change is logged to the console.

Improvements to EditorDelegate

---

Example/PinpointKitExample.xcodeproj/project.pbxproj
Example/Pods/Pods.xcodeproj/xcshareddata/xcschemes/PinpointKit.xcscheme
PinpointKit/PinpointKit.xcodeproj/project.pbxproj

Maintenance work for Xcode 8.2.
* Sets swift version in PinpointKit target of `PinpointKit.xcodeproj`
* Adds a file that was missing when building `PinpointKit.xcodeproj` in its own project (not Example workspace).
* Accepts Xcode’s recommended updates:
1. Create a new Xcode project (Single View Application)
1. Run `pod init`
1. Run `open Podfile` and add `pod 'PinpointKit', :git => 'https://github.com/Lickability/PinpointKit.git', :branch => 'swift-3.0-maintenance'` to your target.
1. Run `pod install`
1. Close the project and open the newly created workspace
1. Choose "Later" when prompted to convert to current Swift syntax
1. Build without any warnings / errors
1. Open `ViewController.swift` and replace the contents with the snippet at the end of this series of steps.
1. Build and Run, …

Swift 3.0 Maintenance

---

PinpointKit/PinpointKit/Sources/ScreenshotDetector/ScreenshotDetector.swift

Follow-up to #199.
Makes `ScreenshotDetector`’s `init` Public. Otherwise, you can’t instantiate `ScreenshotDetector` in your own code.
* Create a new Single View Application Xcode project called `Screenshot`
* In Terminal (in the root of the project), run `pod init`
* Run `open Podfile -a Xcode`
* Replace the contents with:
```
target 'Screenshot' do
use_frameworks!
pod 'PinpointKit', :git => 'https://github.com/Lickability/PinpointKit.git', :branch => 'screenshot-detector-public-init'
pod 'PinpointKit/ScreenshotDetector', :git => 'https://github.com/Lickability/PinpointKit.git', :branch => 'screenshot-detector-public-init'
end
```
* Run `pod install`
* Close the project and open the workspace
* Open `Info.plist` and add an entry for `NSPhotoLibraryUsageDescription`
* Replace …

Makes `ScreenshotDetector`’s `init` Public

---

README.md

Adds build status and dependency manager compatibility badges to the README.
An optional addition that @mliberatore can decide whether to bring into his README branch.

Adds buddybuild build status, CocoaPods, and Carthage badges

---

README.md

Closes #172
- Updates install instructions in the README to refer to `1.0` instead of the `develop` branch.
- Updates references to source files to their relatively-soon-to-be `master` paths. Note that these paths do not yet exist on `master` since [we did a restructure](https://github.com/Lickability/PinpointKit/pull/171). If you’d like to test the URLs, replace `master` with `develop` in the paths.
~~I marked this [DO NOT MERGE] as we’ll want to integrate it just before releasing to reduce potential for confusion with the instructions.~~

README 1.0 Updates

---

README.md

Marks system log collection iOS 9-only and de-emphasizes it as a feature.
* The added link won’t work until #206 and #203 are merged.
* There’s other information about logging in the "Customization" section, but I think the details there can remain. I’d like your opinion, though:
> * Supply your own console log collector that aggregates messages from your third-party logging framework of choice by conforming to [`LogCollector`](https://github.com/Lickability/PinpointKit/blob/master/PinpointKit/PinpointKit/Sources/Core/LogCollector.swift)
> * Change how logs are viewed by creating your own view controller conforming to [`LogViewer`](https://github.com/Lickability/PinpointKit/blob/master/PinpointKit/PinpointKit/Sources/Core/LogViewer.swift).

README Updates for Logging Feature

---

PinpointKit/PinpointKit/Sources/Core/FeedbackTableViewDataSource.swift
PinpointKit/PinpointKit/Sources/Core/SystemLogCollector.swift
PinpointKit/PinpointKitTests/SystemLogCollectorTests.swift

Closes #205.
See description of issue at #205, and the `- warning:` on the initializer in code. This prevents the logging section/cell from displaying on devices that can’t use ASL.
The rest of the code to support logging is in place, and if a 3rd-party logging system were used, it could be made to conform to `LogCollector` and replace `SystemLogCollector` via customization.
1. Run the Example project on an iOS 9.x device
1. Ensure the logging cell is there, and tapping the accessory button takes you to the log view controller with the test log present.
Ensure that logs.txt is attached to an email when sending feedback.
1. Run the Example project on an iOS 10.0 device
1. Ensure the log cell is not present at all, and no logs.txt i

Hides Default Logging Capabilities on iOS 10+

---

PinpointKit/PinpointKit/Sources/ScreenshotDetector/ScreenshotDetector.swift

Closes #211
Fixes two issues with `ScreenshotDetector` brought up in #211:
1. The permission alert for accessing the user’s photo library was appearing prematurely. Now it appears at the time we need to first access the photo library.
1. The fetched screenshot delivered in the delegate was the second-to-most-recent screenshot in the user’s library. We now wait for a change to the photo library before fetching the screenshot to deliver.
* Create a new "Single View Application" in Xcode
* In Terminal.app, `cd` to its directory, and run `pod init`
* Open the Podfile and add the following two lines within your target:
```
pod 'PinpointKit', :git => 'https://github.com/Lickability/PinpointKit.git', :branch => 'screenshot-detector-fixes'
pod 'PinpointKit/ScreenshotDetector', :git => …
```

ScreenshotDetector Fixes

---

PinpointKit/PinpointKit/Sources/Core/Configuration.swift

Closes #222 
Fixes a compiler error caused by modifying `feedbackController`, a `let` constant, in `init` which used to be permitted.
In the latest Xcode 9 beta, run `PinpointKitExample` and smoke test. No compiler errors should occur.
I’ve filed several other unrelated Xcode 9 / iOS 11 SDK issues, but if you see any others while on this branch in the beta, please let me know.

Fixes Swift Swift 3.2 Compiler Error

---

README.md

We just released `1.1.0` but didn’t update our `README.md`, so it’s now out of date. This fixes that.
Read over the diff.

Updates README for Latest Version and Requirements

---

PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift

This brings the changes for #220 into `master`, with one code change to fix a variable reference. The original body of PR #220 is reproduced below for reference.
---
Closes #219.
Previously, if the user clicked `Send` and the `MailSender` experienced a failure (e.g. when there are no mail accounts set up), nothing would happen in the GUI. There was also no method in `PinpointKitDelegate` to correspond to `didFailToSend` in `SenderDelegate`.
This commit adds an alert popup to `PinpointKit` to solve the first problem, and a `didFailToSend` method to `PinpointKitDelegate` for the second. The latter takes the original `Error` as a parameter in case developers want to use it present more specific messages.
Ensure that the mailer will encounter an error (the easiest way is to run the example …

Add mail failure alert

---

Example/PinpointKitExample/ViewController.swift
PinpointKit/PinpointKit/Sources/Core/FeedbackConfiguration.swift
PinpointKit/PinpointKit/Sources/Core/FeedbackNavigationController.swift
PinpointKit/PinpointKit/Sources/Core/FeedbackViewController.swift
PinpointKit/PinpointKit/Sources/Core/NavigationController.swift

Adds presentation style to feedback configuration.
Reloads tableView upon dismissing the editor.
This PR allows the customisation of the FeedbackView/NavigationController's `modalPresentationStyle` (current default is `fullScreen`). I added the property `presentationStyle` to the `Feedback's Configuration` struct (defaults like before to `fullScreen`).
Furthermore we added a tableView reload to the `editorWillDismiss` callback so that not only the `annotedScreenshot` will be assigned, but also the new annoted screenshot will be shown by explicitly reloading the tableView. Using the previous 'fullScreen' presentationMode this wasn't necessary, since it that case the tableView was always implicitly reloaded.
Run the example application like before - it will be presented as a 'formSheet'. …

Allows customization of modal presentation style

---

PinpointKit/PinpointKit/Sources/Core/MailSender.swift
PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift

Closes #242 
Fixes the issue where tapping "Send" with no mail accounts, and no other configuration specified wouldn’t display the alert.
1. Run the example app in a clean simulator
1. Tap "Send"
N/A

Fix for Showing the Mail Compose Failure Alert

---

PinpointKit/PinpointKit/Sources/Core/UIBarButtonItem+TitleTextAttributeStates.swift

Small follow-up to #244. The following was printing to the console:
> [Assert] button text attributes only respected for UIControlStateNormal, UIControlStateHighlighted, UIControlStateDisabled and UIControlStateFocused. state = 4 is interpreted as UIControlStateHighlighted.
I was using `.selected`, which is not respected, and have now changed it to `.focused`.
Same steps as #244 
N/A

Small Fix to UIBarButtonItem+TitleTextAttributeStates

---

PinpointKit/PinpointKit.xcodeproj/project.pbxproj

Closes #247 
Adds fonts to the PinpointKit Xcode Project’s Copy Bundle Resources Phase to fix the fonts not appearing when manually installing the framework.
Follow the steps for installing via CocoaPods, Carthage, and Manually, but replace versions or branch names like those below. Smoke test the framework, making sure the custom fonts are used, and that there are no console logs about resources, or anything else you could think of to indicate that this change has unintended side-effects.
**CocoaPods**
```
pod 'PinpointKit', :git => 'https://github.com/Lickability/PinpointKit.git', :branch => 'add-fonts-to-pinpoint-kit-target'
```
**Carthage**
```
github "Lickability/PinpointKit" "add-fonts-to-pinpoint-kit-target"
```
**Manually**
```
git init
git submodule add -b …
```

Fixes Custom Fonts Not Appearing When Installing PinpointKit Manually

---

PinpointKit/PinpointKit/Resources/PinpointKit.xcassets/Segmented Control/ArrowIcon.imageset/Contents.json
PinpointKit/PinpointKit/Resources/PinpointKit.xcassets/Segmented Control/BlurIcon.imageset/Contents.json
PinpointKit/PinpointKit/Resources/PinpointKit.xcassets/Segmented Control/BoxIcon.imageset/Contents.json
PinpointKit/PinpointKit/Sources/Core/FeedbackNavigationController.swift
PinpointKit/PinpointKit/Sources/Core/FeedbackViewController.swift
PinpointKit/PinpointKit/Sources/Core/InterfaceCustomization.swift

Allows to customize:
1. Status bar appearance, so it is readable on dark backgrounds
2. The color of the navigation bar title (global `UIAppearance` is overridden by PinpointKit because it sets `titleTextAttributes` 
3. Render glyphs in segmented color as template images to adopt the tint color
This is how it looks in a darker environment:

Allow deeper customization

---

PinpointKit/PinpointKit/Sources/Core/Editing/EditorDelegate.swift
PinpointKit/PinpointKit/Sources/Core/FeedbackViewController.swift
PinpointKit/PinpointKit/Sources/Core/InterfaceCustomization.swift
PinpointKit/PinpointKit/Sources/Core/NSBundle+PinpointKit.swift
PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift
PinpointKit/PinpointKit/Sources/Core/Sender.swift
PinpointKit/PinpointKit/Sources/Core/StrokeLayoutManager.swift
PinpointKit/PinpointKit/Sources/Core/TextAnnotationView.swift
PinpointKit/PinpointKit/Sources/Core/UIColor+Palette.swift
PinpointKit/PinpointKit/Sources/Core/UIGestureRecognizer+FailRecognizing.swift
PinpointKit/PinpointKit/Sources/Core/UIView+PinpointKit.swift

Makes a small style pass covering the following:
* Documentation
* Docs end in periods.
* Docs that reference symbols reference the appropriate ones (e.g. `NSBundle` → `Bundle`).
* Symbols referenced in docs are wrapped in back-ticks.
* Drops `NSAttributedStringKey` and `UIColor` prefixes where type inference makes them unnecessary.
Build and run, and do a quick feature smoke test. Nothing of substance was modified.
N/A

Style Consistency Pass

---

Example/PinpointKitExample/Info.plist
Example/Podfile.lock
Example/Pods/Local Podspecs/PinpointKit.podspec.json
Example/Pods/Manifest.lock
Example/Pods/Pods.xcodeproj/project.pbxproj
Example/Pods/Target Support Files/PinpointKit/Info.plist
PinpointKit.podspec.json
PinpointKit/PinpointKit/Info.plist
README.md

Prepares a release for version 1.3.0
Compare to the 1.2.0 version bump PR #241 
* The project file changes in the example project were the result of `bundle exec pod install`.
* Note that a release will not happen immediately after this is merged. All install methods will be tested with these changes before signing off on 1.3.0.

Bump Version to 1.3.0

---

PinpointKit.podspec.json

Closes #[255](https://github.com/Lickability/PinpointKit/issues/255)
Defines the version of the Swift compiler used to build the framework.
- `pod install` into an app target, make sure it compiles and has `4.2` as its `SWIFT_VERSION` Xcode target build setting in `Pods.xcodeproj`
- (optional) `pod install` a podspec that declares PinpointKit a dependency

add swift_version attribute to podspec

---

PinpointKit/PinpointKit/Sources/Core/FeedbackConfiguration.swift
PinpointKit/PinpointKit/Sources/Core/MailSender.swift
PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift

We are using PinpointKit in [Flighty](https://www.flightyapp.com) to send user feedback to [Front](http://frontapp.com). If the image is attached to a plain-text email, it will be shown as an attachment. But if the email is HTML, the image is shown inline which makes understanding reports in Front way easier as you don't have to go back and forth.
If you think this is not something you want to have in PinpointKit, feel free to just close this PR 😄

Allow HTML body content

---

Example/PinpointKitExample/Base.lproj/Main.storyboard
PinpointKit/PinpointKit/Sources/Core/InterfaceCustomization.swift

Closes #271
* Fixes a dark mode bug reported by @rjonsey where the navigation bar title was invisible.
* Updates colors in sample projet.
Followed steps in #271

Fixes Dark Mode Navigation Bar Bug

---

PinpointKit/PinpointKit/Sources/Core/ScreenshotCell.swift

Closes #276 
When building / deploying for iOS 14, tapping the screenshot button wasn’t working. This is due to the fact that the contents of the cell were beneath the cell’s content view, which was getting the touch events. This didn’t seem to bite us until iOS 14, but the fix is just to properly add / pin to the cell’s content view. I checked the other cell, `CheckmarkCell` to be certain, and we’re not adding subviews there, so no similar issue exists. 
On iOS 11, 12, 13, 14:
1. Launch the example app.
1. Tap the screenshot.
1. See the editor.
N/A

Fixes Inability to Tap Screenshot on iOS 14

---

Example/PinpointKitExample.xcodeproj/project.pbxproj
Example/Podfile.lock
Example/Pods/Local Podspecs/PinpointKit.podspec.json
Example/Pods/Manifest.lock
Example/Pods/Target Support Files/PinpointKit/Info.plist
PinpointKit.podspec.json
PinpointKit/PinpointKit.xcodeproj/project.pbxproj
README.md

Prepares a release for version 1.5.0
Compare to the 1.4.0 version bump PR #274   
* Note that a release will not happen immediately after this is merged. All install methods will be tested with these changes before signing off on 1.4.0.

Bumps version to 1.5.0

---

PinpointKit/PinpointKit/Sources/Core/Editing/EditImageViewController.swift

Closes N/A
This PR fixes warnings related to UIMenuController API.
- 'setTargetRect(_:in:)' was deprecated in iOS 13.0: Use showMenuFromView:rect: instead.
- 'setMenuVisible(_:animated:)' was deprecated in iOS 13.0: Use showMenuFromView:rect: or hideMenuFromView: instead.
Build in iOS 13+.
- https://developer.apple.com/documentation/uikit/uimenucontroller/1622812-settargetrect
- https://developer.apple.com/documentation/uikit/uimenucontroller/1622819-setmenuvisible

Fix warnings related to UIMenuController API

---

.gitignore
Package.swift
PinpointKit/PinpointKit/Sources/ASLLogger/ASLLogger.h
PinpointKit/PinpointKit/Sources/ASLLogger/ASLLogger.m
PinpointKit/PinpointKit/Sources/Core/Editing/AnnotationViewFactory.swift
PinpointKit/PinpointKit/Sources/Core/Editing/Editor.swift
PinpointKit/PinpointKit/Sources/Core/Editing/EditorDelegate.swift
PinpointKit/PinpointKit/Sources/Core/FeedbackCollector.swift
PinpointKit/PinpointKit/Sources/Core/FeedbackConfiguration.swift
PinpointKit/PinpointKit/Sources/Core/InterfaceCustomization.swift
PinpointKit/PinpointKit/Sources/Core/LogViewer.swift
PinpointKit/PinpointKit/Sources/Core/NSBundle+PinpointKit.swift
PinpointKit/PinpointKit/Sources/Core/PinpointKit+ShakePresentation.swift
PinpointKit/PinpointKit/Sources/Core/PinpointKit.swift
PinpointKit/PinpointKit/Sources/Core/Screenshotter.swift
PinpointKit/PinpointKit/Sources/Core/SystemLogCollector.swift
PinpointKit/PinpointKit/Sources/Core/UIView+PinpointKit.swift

Closes #264 
This PR adds Swift Package Manager support to this library.
Run the following command in the root directory:
```
swift build -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios14.0-simulator"
```
Or add this library as a Swift Package to your project.
This package contains ASLLogger target (Objective-C) and PinpointKit target (Swift) because SPM doesn't support mixed language target at least now.

Add Swift Package Manager support

---

PinpointKit/PinpointKit/Sources/Core/ShakeDetectingWindow.swift

New iOS apps should provide a scene delegate and support multiple windows. 
This change is to support this with ShakeDetectingWindow
Closes #
Adds support to create ShakeDetectingWindow when implementing SceneDelegate.

Added UIWindowScene support
